### ISSUE TITLE
Please push release tags

### ISSUE THREAD

**Issue by rillian** [paritytech/libsecp256k1#120]
The v0.3.1 release has a nice signed tag in the github repo, but no other releases do.

When auditing dependency updates, it's helpful if the upstream repo has clear tags for each published release, so simple `git diff` and `git log` can be used to review changes. It would be great if you could push tags for at least the recent releases to make this possible.

In the meantime, here are some corresponding commits according to the crates.io package metadata
| version | commit id |
|------|--------------------|
|0.1.15|aba3d3ff7a7d8d386c0cd44635c02c1d599c6d43|
|0.2.2|22e9297118c8c8c646082151a439e05c58b03f9b|
|0.3.1|c05c4e0014aacf5f0599aee519f2d705caad4983|
|0.3.5|d0eedf2569bea15b453d53fa53ef95302ba1d59e|
|0.5.0|98d7025f577c99e6ae9b74b6fb428404d6177fa5|
|0.6.0|e5095a8930de6f2ae2003c164eba9bfb7ce2f628|
|0.7.0|34293f502aeedaefc312993278c5402b221f7f7e|

Related to #91 and #104.

**Comment by sorpaas** [comment]
All tags have been pushed.
