### ISSUE TITLE
About link is 404

### ISSUE THREAD

**Issue by rillian** [paritytech/libsecp256k1#121]
In the "About" section of the github repo, there's a link to https://source.that.world/source/libsecp256k1-rs/ under the description, which is 404.

Probably this should just be removed in favour of the crates.io and docs.rs pages.

**Comment by sorpaas** [comment]
It was a left-over as this moved from my personal project. I'll ask around those who have permissions to remove it.

**Comment by TriplEight** [comment]
Done
