### ISSUE TITLE
Consider exposing field, group, and scalar types as public?

### ISSUE THREAD

**Issue by tuxxy** [paritytech/libsecp256k1#23]
Hi, this library is really one-of-a-kind in that it's a pure rust implementation of secp256k1.

Is it at all possible that the authors would consider exposing the field, group, and scalar types as public types so that we can use them for arithmetic in other libraries to build and prototype with? We have a need for this on a library-in-progress from @nucypher and these exposed types would save a ton of work.

**Comment by tuxxy** [comment]
Bump please. There are literally no libraries in the rust ecosystem that support pure rust implementations for these primitives.

**Comment by LLFourn** [comment]
Note: these are public. Look under `curve`.

**Comment by tuxxy** [comment]
Ah, this is fantastic news! The last version I had played with was 0.3.0 which did not expose the arithmetic in the `curve` module.

Thanks for pinging me about this! :)
