### ISSUE TITLE
Discuss tradeoffs involved when using static vs dynamic tables

### ISSUE THREAD

**Issue by dvdplm** [paritytech/libsecp256k1#46]
See https://github.com/paritytech/libsecp256k1/pull/41#issuecomment-605059456

Give users enough info to decide whether they should use static or dynamic tables, e.g. things like:

- binary size
- runtime memory (?)
- cost of table generation
- …

**Comment by sorpaas** [comment]
Users can now choose themselves `static-context` vs `lazy-static-context`.
